on: push

name: Continuous Integration

jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt secrets
        uses: zgosalvez/github-actions-decrypt-secrets@v1
        with:
            secrets_file: .github/workflows/secrets.json.gpg
            map: 'NOVEL_NAME=NOVEL_NAME,NOVEL_LINK=NOVEL_LINK'
        env:
            GPG_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
      - name: Test (Do not expose your actual secrets!)
        run: |
          echo $NOVEL_NAME
          echo $NOVEL_LINK
